var a, b;
a = 10;
b = 20;

document.write("<h2>");
document.write("a=10, b=20");
document.write("<hr />");
document.write("a+b="+(a+b));
document.write("<hr />");
document.write("a-b="+(a-b));
document.write("<hr />");
document.write("a*b="+(a*b));
document.write("<hr />");
document.write("a/b="+(a/b));
document.write("<hr />");
document.write("a%b="+(a%b));
document.write("<hr />");
document.write("a==b="+(a==b));
document.write("<hr />");
document.write("a!=b="+(a!=b));
document.write("<hr />");
document.write("a>b="+(a>b));
document.write("<hr />");
document.write("a<b="+(a<b));
//document.write("<hr />"); 
document.write("a>=b="+(a>=b));
document.write("<hr />");
document.write("a<=b="+(a<=b));
document.write("<hr />");
document.write("대한민국>대한민곡="+("대한민국">"대한민곡"));
document.write("</h2>");